
# Backup of bot.py before reset
# This file is an exact backup created automatically. Do not edit this file if you need to restore.

"""
Full backup of original bot.py

Contains the original implementation with job posting, application workflows,
editor profiles, rating system, and keep-alive webserver.

Restore by copying this file back to bot.py if needed.
"""

# --- Original file contents (start) ---
import os
import json
import random
import discord
from discord.ext import commands
from discord import app_commands
from dotenv import load_dotenv
from datetime import datetime, timedelta
import re

# Import necessary libraries for the web server to keep the bot alive on Replit
from flask import Flask
from threading import Thread

# --- Data Persistence Handlers ---
DATA_FILE = 'bot_data.json'
MAX_APPLICANTS = 20

def load_data():
	"""Loads bot data from a JSON file, or creates an empty one if it doesn't exist."""
	if os.path.exists(DATA_FILE):
		with open(DATA_FILE, 'r') as f:
			data = json.load(f)
			# Add new data structures if they don't exist
			if 'ratings' not in data:
				data['ratings'] = {}
			if 'reviews_channel_id' not in data:
				data['reviews_channel_id'] = None
			if 'editor_profiles' not in data:
				data['editor_profiles'] = {}
			return data
	# Initial data structure for the first time the bot runs
	return {
		"job_id_counter": 0,
		"logs_channel_id": None,
		"job_channel_id": None,
		"ratings": {},
		"reviews_channel_id": None,
		"editor_profiles": {}
	}

def save_data(data):
	"""Saves bot data to a JSON file."""
	with open(DATA_FILE, 'w') as f:
		json.dump(data, f, indent=4)

def validate_url(url):
	"""Simple URL validation"""
	url_pattern = re.compile(
		r'^https?://'  # http:// or https://
		r'(?:(?:[A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?\.)+[A-Z]{2,6}\.?|'  # domain...
		r'localhost|'  # localhost...
		r'\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})'  # ...or ip
		r'(?::\d+)?'  # optional port
		r'(?:/?|[/?]\S+)$', re.IGNORECASE)
	return url_pattern.match(url) is not None

# Load initial data
bot_data = load_data()

# --- Bot Setup ---
load_dotenv()
TOKEN = os.getenv('DISCORD_TOKEN')

intents = discord.Intents.default()
intents.message_content = True
intents.members = True # Required to get member objects for DMs

bot = commands.Bot(command_prefix='!', intents=intents)

# --- Global Data Storage and Utility Functions ---
motivational_quotes = [
	"Every rejection is a redirection.",
	"The secret of getting ahead is getting started.",
	"Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.",
	"Don't be afraid to fail. It's not the end of the world, and in many ways, it's the first step toward learning something new."
]

# A dictionary to store active jobs for applications and to track applicants.
active_jobs = {}

# Software/App options for profiles
SOFTWARE_OPTIONS = [
	"Adobe Premiere Pro", "Adobe After Effects", "Adobe Photoshop", "Adobe Illustrator",
	"DaVinci Resolve", "Final Cut Pro", "Cinema 4D", "Blender", "Sony Vegas Pro",
	"Avid Media Composer", "Adobe Audition", "Logic Pro", "Pro Tools", "Figma",
	"Sketch", "Canva Pro", "Procreate", "Substance Painter", "Maya", "3ds Max"
]

# Niche/Specialization options
NICHE_OPTIONS = [
	"Gaming Content", "Educational Videos", "Music Videos", "Corporate Videos",
	"Social Media Content", "YouTube Shorts", "TikTok Content", "Podcast Editing",
	"Documentary Editing", "Wedding Videos", "Product Commercials", "Explainer Videos",
	"Animation", "Motion Graphics", "Color Grading", "Sound Design", "Thumbnails"
]

async def update_editor_nickname(guild: discord.Guild, editor: discord.Member):
	"""
	Updates an editor's nickname to display their average rating.
	This function will be called whenever a rating is submitted or requested.
	"""
	editor_id = str(editor.id)
	editor_ratings = bot_data['ratings'].get(editor_id)
    
	if not editor_ratings or editor_ratings['total_ratings'] == 0:
		# If no ratings, remove the rating from the nickname if it exists
		if "(" in editor.display_name and "⭐" in editor.display_name:
			try:
				await editor.edit(nick=editor.name)
			except discord.Forbidden:
				print(f"Failed to update nickname for {editor.name} due to insufficient permissions.")
		return

	# Calculate the average rating
	average_rating = editor_ratings['total_score'] / editor_ratings['total_ratings']
    
	# Format the new nickname with the rating
	new_nickname = f"{editor.name} (⭐{average_rating:.1f})"
    
	# Discord has a 32-character limit for nicknames, so we need to truncate if necessary
	if len(new_nickname) > 32:
		new_nickname = f"{editor.name[:25]}...⭐{average_rating:.1f}"
    
	try:
		await editor.edit(nick=new_nickname)
	except discord.Forbidden:
		print(f"Failed to update nickname for {editor.name} due to insufficient permissions. Check the bot's role hierarchy and 'manage nicknames' permission.")
	except Exception as e:
		print(f"An unexpected error occurred while updating {editor.name}'s nickname: {e}")

def get_profile_embed(user: discord.Member, profile_data: dict):
	"""Creates an embed for displaying editor profiles"""
	embed = discord.Embed(
		title=f"📋 Editor Profile: {user.display_name}",
		color=0x9b59b6
	)
	embed.set_thumbnail(url=user.display_avatar.url)
    
	# Basic info
	embed.add_field(name="👤 Discord User", value=user.mention, inline=True)
    
	# Experience
	exp_years = profile_data.get('experience_years', 0)
	if exp_years:
		embed.add_field(name="📅 Experience", value=f"{exp_years} years", inline=True)
    
	# Rating info
	editor_id = str(user.id)
	editor_ratings = bot_data['ratings'].get(editor_id)
	if editor_ratings and editor_ratings['total_ratings'] > 0:
		avg_rating = editor_ratings['total_score'] / editor_ratings['total_ratings']
		embed.add_field(name="⭐ Rating", value=f"{avg_rating:.1f} ({editor_ratings['total_ratings']} reviews)", inline=True)
	else:
		embed.add_field(name="⭐ Rating", value="No ratings yet", inline=True)
    
	# Bio
	if profile_data.get('bio'):
		embed.add_field(name="📝 Bio", value=profile_data['bio'], inline=False)
    
	# Software
	if profile_data.get('software'):
		software_list = ", ".join(profile_data['software'])
		embed.add_field(name="💻 Software/Apps", value=software_list, inline=False)
    
	# Niches
	if profile_data.get('niches'):
		niches_list = ", ".join(profile_data['niches'])
		embed.add_field(name="🎯 Specializations", value=niches_list, inline=False)
    
	# Portfolio
	if profile_data.get('portfolio_links'):
		portfolio_text = "\n".join([f"• {link}" for link in profile_data['portfolio_links']])
		embed.add_field(name="🎨 Portfolio", value=portfolio_text, inline=False)
    
	# Availability
	availability = profile_data.get('availability', 'Not specified')
	embed.add_field(name="📋 Availability", value=availability, inline=True)
    
	# Hourly rate
	if profile_data.get('hourly_rate'):
		embed.add_field(name="💰 Hourly Rate", value=f"${profile_data['hourly_rate']}/hr", inline=True)
    
	embed.set_footer(text=f"Profile created: {profile_data.get('created_at', 'Unknown')}")
    
	return embed

# --- Original file contents (end) ---

